### PR TITLE
Removing 5.6

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: https://github.com/Islandora-Devops/claw-playbook/pull/66 and https://github.com/Islandora-CLAW/CLAW/issues/841

# What does this Pull Request do?

Removes 5.6, unblocking https://github.com/Islandora-Devops/claw-playbook/pull/66 and https://github.com/Islandora-CLAW/CLAW/issues/841

# What's new?
No more PHP 5.6

# How should this be tested?

We can fix https://github.com/Islandora-Devops/claw-playbook/pull/66 and https://github.com/Islandora-CLAW/CLAW/issues/841

@Islandora-CLAW/committers

### CODE REVIEW

**Comment by whikloj** [comment]
@seth-shaw-unlv @Natkeeran I don't know if you got the email about removing support for PHP 5.6.

We are going to make the cut now rather than drag it out. 

If you have any questions/concerns, please let us all know.

Also, @dannylamb sent you invites to the CLAW committer email list. But today when I looked neither of you are on it. Did you receive an invite?

**Comment by seth-shaw-unlv** [comment]
@whikloj & @dannylamb  I don't see an email list invitation in my account.

**Comment by dannylamb** [comment]
@seth-shaw-unlv @Natkeeran I just re-sent invitations.  Let me know if you get them.

**Comment by seth-shaw-unlv** [comment]
@dannylamb got it.

**Comment by whikloj** [comment]
To quote @dannylamb 
> 👋 🎲

**Pull request merged**
