### PR TITLE
Update CONTRIBUTING.md since F4IG is deprecated.

### PR DESCRIPTION
**Pull request by ruebot**
@whikloj @DiegoPino @manez I've updated this to reflect this project post-F4IG retirement. Let me know if you think I should address anything else in it. Happy to add more commits to this PR. Also, let me know if you want me to do a PR against our lovely sprint branch.

### CODE REVIEW

**Comment by DiegoPino** [comment]
:+1:  cool! Will wait 24 hrs to merge if anyone wants to add something (or not). Thanks @ruebot

**Comment by manez** [comment]
Looks good! :+1:  for doing the sprint branch as well. docs_consistency++

**Comment by whikloj** [comment]
:+1:

**Comment by acoburn** [comment]
:+1:

**Pull request merged**
