### PR TITLE
Upgrade to Drupal 8.2

### PR DESCRIPTION
**Pull request by dannylamb**
Addresses https://github.com/Islandora-CLAW/CLAW/issues/392

The REST UI module made a release TODAY that works with 8.2.  We're back in business with no yaml.

### CODE REVIEW

**Comment by whikloj** [comment]
`vagrant up`

**Comment by whikloj** [comment]
Possibly unrelated, but tried to add a new Fedora Resource and got a website error. Apache log says
```
[Thu Nov 10 19:21:35.494767 2016] [:error] [pid 28029] [client 10.0.2.2:57649] Uncaught PHP Exception Symfony\\Component\\Routing\\Exception\\RouteNotFoundException: "Route "entity.fedora_resource.version_history" does not exist." at /var/www/html/drupal/core/lib/Drupal/Core/Routing/RouteProvider.php line 187, referer: http://localhost:8000/admin/structure/fedora_resource/add/rdf_source
```

**Comment by dannylamb** [comment]
not unrelated... other work sneaking through.  let me pull my version stuff out of it.  sry... bad form with git on my part.

**Comment by dannylamb** [comment]
hrm... looks fine on my install.  and the revision stuff isn't there or in the commit.  i was paranoid because i totally added that route in other work, but i sliced it out properly.  i'm going to blast what i've got and re-vagrant up to double check.  tabula rasa.

**Comment by dannylamb** [comment]
screenshot from 2016-11-14 09-57-42

:( 

Fresh install didn't reproduce?  Can anyone try?

@whikloj Shall we start the vbox/vagrant version dance?  Vbox 5.0.24_Ubuntu / Vagrant 1.8.1 on Ubuntu 16.04

**Comment by whikloj** [comment]
My islandora submodule is different and I can't get it to go back to normal. Death to submodules.

**Comment by dannylamb** [comment]
I made sure I had everything pushed up, and then I clobbered my directory and re-cloned.  I don't trust the submodules either.

**Comment by DiegoPino** [comment]
I did a fresh install and could not reproduce the error this pull fixes, so i think we have deployment async problems (deployment version vectors??). So if anyone can confirm this is working then i'm fine.

**Comment by dannylamb** [comment]
Yes.  I think at this point we should consider pulling install out into its own repo, as well.  It's confusing to bundle it with this, which I guess is just for releases, really.

**Comment by dannylamb** [comment]
Is someone ok merging this?

**Comment by dannylamb** [comment]
Merged with upstream to get rid of a conflict.  Good to go now.

**Comment by dannylamb** [comment]
Thx @ruebot

**Pull request merged**
