### PR TITLE
Create creating collection.md

### PR DESCRIPTION
**Pull request by alexkent0**
Text for documentation on creating a collection.

**GitHub Issue**: (link)

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)

# What does this Pull Request do?

User documentation on creating a collection for Islandora 8.

# Interested parties
@mjordan, @dannylamb, @Islandora-CLAW/committers

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
@alexkent0, you should save the screenshots to the assets directory and create links to them in the appropriate spots in your markdown. E.g. (assuming the first screenshot was named creating-collections-add-content-link.png) you would enter it like this:
```
Click on Add content. This is under Tools.

![Alt-text for the image](../assets/creating-collections-add-content-link.png)

Then click on Repository Item. A collection is considered a "Repository Item."
```
Also, you should replace the name in the filename with a hyphen: 'creating-collection.md'

**Comment by alexkent0** [comment]
Seth, thanks again. I loaded them to the directory but now I can't find where the images went. Where can I find the directory and the actual images to make the links in the documentation? I'm a complete newbie to this process. Thanks!

**Comment by seth-shaw-unlv** [comment]
Glad to help, @alexkent0. You have two separate branches going on here: patch-2 and patch-3 and each have separate upload forms. The link on the other PR adds files to that corresponding branch. This branch uses https://github.com/alexkent0/CLAW/upload/patch-3/docs/assets. Also, rename the files to be lower-case and use hyphens instead of spaces before uploading.

**Comment by alexkent0** [comment]
Thanks @seth-shaw-unlv. I think I have this one updated correctly, with links to screenshots: https://github.com/Islandora-CLAW/CLAW/pull/1048/commits/cc9d9db581f22626ea6456068f48212b4cf57162

**Comment by seth-shaw-unlv** [comment]
@alexkent0 three things:

1. The image paths should be relational. The paths you have there ('docs/assets/repository item.jpg') would point to a docs/assets directory inside the user-documentation directory, but we want to point to the assets directory sitting at the same level as the user-documentation directory, so change your 'docs/assets/' to '../assets/' and that will be fine.
1. The [commit you pointed to](https://github.com/Islandora-CLAW/CLAW/commit/cc9d9db581f22626ea6456068f48212b4cf57162) in [your comment](https://github.com/Islandora-CLAW/CLAW/pull/1047#issuecomment-470621086) wasn't on your branch. Make sure the changes (for this PR) are in the https://github.com/alexkent0/CLAW/tree/patch-2/docs repository and branch.
1. The files should not use spaces in their file names. Use hyphens or underscores instead of spaces and make sure the names are all lower-case.

**Comment by manez** [comment]
Hang in there, @alexkent0. It's a labyrinth at first, but I promise it gets easier once you get into it 👍

**Comment by dannylamb** [comment]
Superseded by https://github.com/Islandora-CLAW/CLAW/pull/1084

**Pull request closed without merging**
