### PR TITLE
Added windows ssh connect instructions

### PR DESCRIPTION
**Pull request by jyobb**

### CODE REVIEW

**Comment by br2490** [comment]
@jyobb, hey! Did you try the `vagrant ssh` command from Vagrant directory? If folks are using `vagrant up` to bring a machine up I recommend keeping it simple with `vagrant ssh`! AFAIK booting the VM from VMWare should be _strongly discouraged_ as it will break links and `yada-yada` on Windows. 

What do you think @jyobb? It also looks like there are a few guides out there that do already cover this topic, perhaps they could be included in a note for more advanced users?

-benji

***vanishes***

**Comment by jyobb** [comment]
I started up the stack with vagrant up.   When I tried vagrant ssh I
received an error saying that no ssh client was found.

John

**Comment by dannylamb** [comment]
Hrm... sounds like windows vagrant config at play here?  You may need to make sure `ssh.exe` is on your path so vagrant can find it.

**Comment by jyobb** [comment]
Yea.  I have a few issues :( Fedora is not being installed for me either.
Danny you are correct. I just need to adjust my path.  I had no idea that
ssh was installed.  I'm not really a windows guy but am muddling my way
through

John

**Comment by br2490** [comment]
@dannylamb @jyobb Windows is a PIA. IIRC Vagrant should, upon install, modify the system environment to reflect the fact that... well... Windows doesn't have many useful nix tools (Ubuntu Bash was a nice try). Ultimately I've found that in most situations issues are caused by permissions, which means you need to right click on and "Run as Administrator" BOTH the cmd.exe or ps.exe (PowerShell) you'll run `vagrant up` from AND VirtualBox. 

I don't know if the issues I'm recalling are resolved, but @jyobb when it feels like the Window's walls are closing in, elevate those permissions ;)

Sorry for adding this in the comments and not doing a proper pull. I'm 👎

**Comment by jyobb** [comment]
I'll try bumping up the permissions and rebuilding the vagrant box. I'm
most concerned about the lack of fedora.

John

**Comment by edf** [comment]
I had problems with timeouts with the fedora war wget download in the install/scripts/fcrepo.sh.  I copied the war file manually into $DOWNLOAD_DIR before starting vagrant up to work around the timeouts.  

It might be worth checking the tomcat logs for errors.

**Comment by dannylamb** [comment]
@jyobb Did you ever get the Fedora issue figured out?

**Comment by jyobb** [comment]
Danny,

I have not had time to look at my vagrant box issues.  I was tasked with
creating a new islandora instance and adding blazegraph to 3 instances.
I'm trying to get back to the new version but have been overloaded with
other work.

John

**Comment by br2490** [comment]
I have a few hours today and I'd be glad to lend a hand (if y'all will have me and @jyobb doesn't mind). If 👍 which branch should I be attempting to `vagrant up`? 

-benji

**Comment by jyobb** [comment]
Go for it. I'm swamped with upgrading.

John

**Comment by dannylamb** [comment]
@br2490 Master is what you should attempt to build.

**Comment by br2490** [comment]
@ruebot that is an unfortunate no. I tried to spin one up and encountered issues _before_ getting anywhere. I made the assumption due to absence things had progressed to the point where I was afraid the time required to really reengage was unavailable. I should have made this clearer sooner.

I'd really like to reengage.

**Pull request closed without merging**
