### PR TITLE
Sprint 002 issue 150 reup

### PR DESCRIPTION
**Pull request by br2490**
Clean pull request.
Continues work on #150 after resolving issues with Windows Vagrants...

Also note that the PSR2 thingy I use removed, which it probably shouldn't have.
use Symfony\Component\HttpFoundation\Response;

@ruebot @whikloj @DiegoPino This PR is better than my last.

### CODE REVIEW

**Comment by br2490** [comment]
Yes.

**Comment by whikloj** [comment]
I'll test this, but I think the issue was when @DiegoDino and I spoke about this. We figured this should probably go into the (yet to be created) PcdmObjectService. That way we leave the core delete functionality alone.

If it works, I'll see if I can move it via a PR on @br2490's PR.

**Comment by whikloj** [comment]
Actually, there is no way to commit this to a new file without losing the contributions. So I'll test it tomorrow and if it works, we can merge it and then create a new task to create the PcdmObjectService and move this delete functionality there instead of leaving it here.

But @br2490, it looks like you have merge conflicts. Can you rebase this on origin/sprint-002?

**Comment by br2490** [comment]
@whikloj assuming I've managed the merge + Travis likes my code compliance, I think we're okay.

**Comment by br2490** [comment]
Dear Travis,

It has come to my attention you're aware that I lint files like I clean my lint trap; infrequently and poorly. 
Please accept my current commit as recompense for my haphazardness. 

Best,
Ben - still totally on vacation.

**Comment by br2490** [comment]
@ruebot I've got this, it's just two lines that are too long. ;)

**Pull request merged**
