### PR TITLE
Test for a composer path and use it with PHP and no memory limit.

### PR DESCRIPTION
**Pull request by whikloj**
@Islandora-CLAW/committers

This along with changes in each `.travis.yml` seems to resolve the OOM errors.

### CODE REVIEW

**Comment by whikloj** [comment]
Not sure now if this is necessary as the simple changes in the individual module `.travis.yml` seems to have resolved the OOM errors. This might help but could also just be confusing the matter?

**Comment by dannylamb** [comment]
@whikloj Do builds still fail without this?

**Comment by whikloj** [comment]
@dannylamb no, the above linked jsonld PR-27 passed without this.

**Comment by whikloj** [comment]
@dannylamb the only thing I am wondering, and I may have to test, is if we should add `memory_limit = -1` to **all** PHP versions using something like the `php56.ini` file here and then perhaps we can not add `-dmemory_limit=-1` to each use of `php`.

The downside is we lose the flexibility of where we decide to allow for unlimited memory usage...not sure.

**Comment by dannylamb** [comment]
@whikloj Personally, I say set them all to max and let it ride :wave: :game_die:

**Comment by whikloj** [comment]
Ok, I'll try adjusting this and jsonld and see if I can get something cleaner.

**Comment by dannylamb** [comment]
Hoping this will help with Islandora-CLAW/islandora#86

**Pull request merged**
