### PR TITLE
add routeIds and descriptions

### PR DESCRIPTION
**Pull request by acoburn**
It's good practice to have distinctive routeId values (and descriptions) for your camel routes, especially when using JMX or other monitoring services (such as hawt.io).

### CODE REVIEW

**Comment by daniel-dgi** [comment]
somehwere in that wall of text is what's up with the xml.  you can ignore all  the scripting factory nonsense.  if you install camel-script wihotut camel-script-jruby or camel-script-groovy, you get those errors.

**Comment by acoburn** [comment]
... what @daniel-dgi said.

But actually, I'd hold off on this one and #48 for now. I think having a testing framework in place first makes more sense. And once #46 is merged, we can move forward with that.

**Comment by daniel-dgi** [comment]
at a closer look, no route with id 'get'.  so something's expecting it and it's not there, or there's a naming conflict on 'get'

**Comment by acoburn** [comment]
@daniel-dgi is correct -- I renamed some of the context ids (there were several "get" ids, etc), but that is causing other errors. In short, this PR has some problems.

**Comment by DiegoPino** [comment]
@daniel-dgi, newbie here: maybe we need to update those https://github.com/Islandora-Labs/islandora/blob/b7beb393a1713f2b131be95d5878a7e05eed88b7/camel/services/basic-image-service/src/main/resources/OSGI-INF/blueprint/blueprint.xml#L20-L23
to the new named route context ids?

**Comment by daniel-dgi** [comment]
You nailed it.  getBasicImage, postBasicImage, etc...

**Comment by DiegoPino** [comment]
Yeah, also for https://github.com/Islandora-Labs/islandora/blob/b7beb393a1713f2b131be95d5878a7e05eed88b7/camel/services/collection-service/src/main/resources/OSGI-INF/blueprint/blueprint.xml#L46-L49. :smile:

**Comment by DiegoPino** [comment]
@ruebot, i think we are ready for another test. :pray:

**Comment by DiegoPino** [comment]
@ruebot++

**Comment by acoburn** [comment]
I've rebased this against master, so it should be easier to test

**Comment by DiegoPino** [comment]
@acoburn and @ruebot , since rebase removed pulls against pulls i will do the process again in the afternoon after syncing your branch locally. thanks

**Comment by acoburn** [comment]
@DiegoPino I clearly screwed that up. I will merge https://github.com/acoburn/islandora/pull/2 and https://github.com/acoburn/islandora/pull/3 back into this PR.

**Comment by DiegoPino** [comment]
hey @acoburn, don't worry, i will do this later.

**Comment by acoburn** [comment]
@DiegoPino your commits are now part of this PR

**Comment by DiegoPino** [comment]
@acoburn++, you are awesome, thanks a lot!

**Comment by DiegoPino** [comment]
@ruebot or @acoburn, don't want to be a pain, but did you test on a fresh vagrant (destroy - up) after #46? I was searching for the problem on this one so i did a pre-test using current 7.x-2.x only. I got a non functional islandora2, karaf did not deploy the features. I get warnings during maven compile (no fatal errors so the vagrant spins, but i think there are some references wrong) , my humble opinion is that #46 is not complete. E.g, the karaf deployment scripts don't match the new unified structure. Try /opt/karaf/bin/client < $HOME/islandora/install/configs/karaf/services.script, you will get errors.

**Comment by acoburn** [comment]
@ruebot @DiegoPino my approach is somewhat different, which is to start writing a test suite. There are things in this PR that I need for the tests, so I'm wondering whether to a) add stubs for now (i.e. route IDs) and handle any conflicts later or b) hold off on this PR until the tests are farther along or c) cherry pick from this PR and integrate those changes into the test suite as I go along.

I'd like to do the tests in stages. Once I get a framework in place, you'll easily see how to contribute to the test -- testing in camel is not as straight forward as simply writing the routes!

**Comment by DiegoPino** [comment]
@ruebot - did a second clean vagrant without luck. I'm clueless?

**Comment by acoburn** [comment]
closing this for now -- I may reopen it later, but I'd like to see a testing framework in place first, similar to #65

**Pull request closed without merging**
