### PR TITLE
Sprint 002 Issue 211, documentation of micro services.

### PR DESCRIPTION
**Pull request by br2490**
This PR addresses documentation issue #211. See commit history for versioning of the document - 1) intial conversion 2) changing ports to reflect php microservices and added link to original document. 

Also, @8282, whomever you are, please ignore this and my commit message ;) :+1: .

### CODE REVIEW

**Comment by br2490** [comment]
and tagging @Islandora-CLAW/7-x-2-x-committers

**Comment by whikloj** [comment]
Sorry I must have missed this conversation. We have documentation as README.md files for each service in the services directory. Is this meant to bring that information into one location? 'Cause we'll have to maintain it in two places.

[Top Level Services Directory](https://github.com/Islandora-CLAW/CLAW/tree/sprint-002/services)
[ResourceService](https://github.com/Islandora-CLAW/CLAW/tree/sprint-002/services/ResourceService)
[TransactionService](https://github.com/Islandora-CLAW/CLAW/tree/sprint-002/services/TransactionService)
[CollectionService](https://github.com/Islandora-CLAW/CLAW/tree/sprint-002/services/CollectionService)

**Comment by DiegoPino** [comment]
@whikloj, this goes into: docs/technical-documentation/islandora-middleware-services-api.md
 i feel it's complimentary to each readme.md. @ruebot do you know if .md files allow includes, or can be generated from external ones? Maybe we could in the future split this into the individual readme files and then make a composite one (this one) in  that feeds from them? That could solve your concern Jared?

**Comment by br2490** [comment]
#211 was a task simply to copy-pasta the original by Danny to MD so it
could be worked on more actively. If Diego's suggestion is the way to go
++, but I'm afraid I might not know what to do in terms of linking or
transforming many docs to one.

On Sun, May 1, 2016 at 12:04 PM, Diego Pino Navarro <
notifications@github.com> wrote:

> @whikloj <https://github.com/whikloj>, this goes into:
> docs/technical-documentation/islandora-middleware-services-api.md
> i feel it's complimentary to each readme.md. @ruebot
> <https://github.com/ruebot> do you know if .md files allow includes, or
> can be generated from external ones? Maybe we could in the future split
> this into the individual readme files and then make a composite one (this
> one) in that feeds from them? That could solve your concern Jared?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Islandora-CLAW/CLAW/pull/216#issuecomment-216052025>
>



-- 
Benjamin Rosner

Instructional Applications Developer
Library and Academic Information Services
Sulzberger Hall Annex, Barnard College
p: 212-854-9005

**Comment by whikloj** [comment]
@DiegoPino there doesn't seem to be any way to include the content ([see issue here](https://github.com/github/markup/issues/172#issuecomment-33241601)).

I don't want to create a long drawn out conversation over this. So you are welcome to merge this as is.

**Pull request merged**
