### PR TITLE
added basic tests to image service

### PR DESCRIPTION
**Pull request by acoburn**
Supersedes #58

### CODE REVIEW

**Comment by DiegoPino** [comment]
hey @acoburn , awesome, looks very good to me :+1:

**Comment by acoburn** [comment]
@ruebot I am going to close #47 and #48 for now. I may reopen them later, but I'd like a testing framework in place first. This PR definitely depends on #46 which is in the `-dev` branch. Is that what you're asking?

**Comment by whikloj** [comment]
@acoburn with #83 and #119 complete, do you want to close or update this PR? If you are busy (as I am sure you are), I can try to rebase it.

**Comment by acoburn** [comment]
@whikloj thanks for the reminder. Should this PR target the -dev branch or the main 7.x-2.x branch?

**Comment by whikloj** [comment]
@acoburn I would say the main branch. 
I believe we are deleting the -dev branch, am I correct @ruebot @daniel-dgi @DiegoPino??

**Comment by acoburn** [comment]
@whikloj @ruebot thanks! I'll need to close this and re-open the PR against the other branch then.

**Pull request closed without merging**
