### PR TITLE
Update Lobster / to replace the cheese burger

### PR DESCRIPTION
**Pull request by DonRichards**
Starting a conversation on this..
Thoughts? 
Suggestions on design, layout, text? 

Looking for deeper meaning for each section and thought this would be a good place to mine for comments and suggestions.

**GitHub Issue**: N/A

# What does this Pull Request do?
Illustrates

# What's new?
Image

# How should this be tested?
N/A

# Additional Notes:
Looking for suggestions. 

Also, going to smooth out the puzzle pieces. Just did this roughly during the last CLAW call. 

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora-CLAW/committers

### CODE REVIEW

**Comment by dannylamb** [comment]
What do SB, ST, LS, and T represent?

**Comment by manez** [comment]
I like the concept, but I'd rather he were face-on, with two claws. Still not entirely sure what the claws would be, but he'd read more lobster and less shrimp.

**Comment by DonRichards** [comment]
@dannylamb  Segment Bottom, Segment top, Left Segment, tail. Just ways for people to give clear feedback for labels. These should be replaced before this is merged. Needing suggestions for what should go where. I filled in the areas I could remember we discussed but I'm sure I missed a lot. 

@manez I can do that. I'm not sure how to keep it lobster like if it's face on but I can easily do a top view if you'd prefer.

**Comment by dannylamb** [comment]
@DonRichards Gotcha.  That's for us to decide. :+1:

**Comment by bryjbrown** [comment]
So I feel the thing that the burger diagram got right was that it was simple and intuitive; a burger is a thing that is configured out of other things (patty, buns, condiments, etc), and its more than the sum of its parts. Everybody knows what a burger is, and the real genius is that you need at least buns (Drupal & Fedora) and a patty (Islandora module + Tuque + Drupal Auth Filter?) to be a Minimum Viable Burger (MVB) but beyond that, everything else is optional. Solr isn't required but it makes things a lot better (most people tend to prefer cheeseburgers), and the sauces & veggies are added according to personal tastes. The burger metaphor obviously had its limits, but it was accessible and uncomplicated and helped people to make sense of a complicated system.

We are discussing this in the context of updating the 8.x lobster drawing as the spiritual successor to the 7.x burger diagram, but I think it would be appropriate to take a step back and consider whether a lobster is the right metaphor at all, or if we might be able to think of a new metaphor that expresses the concept of what the Islandora 8.x stack is much more concisely. The burger was used to show people who weren't familiar with the 7.x stack what it was at a very high level, and with this in mind whatever we choose for 8.x needs to be concise, clear and intuitive. The lobster is a wonderful mascot for the Islandora community, but I don't think there's anything about a lobster's anatomy that intuitively maps to parts of an 8.x (how do you decide what the claw or the tail or the antennae are, and does that actually help express anything of value to the person reading it that helps them understand the stack better in any real way?).

I don't wanna just naysay and tear down other people's work, so I'll suggest some possible new things that could be used as a diagram:
- a starfish (still an aquatic animal, each limb terminates in one of the important applications, with the body itself being camel and the limbs being camel queues)
- A series of businesses and their parking lots, all connected in the middle by a roundabout (traffic metaphors are useful here since we are trucking copies of things back and forth, each business does a different thing and the parking lot resembles all the data they keep track of)
- an office with different departments (each department is a different application, they all send memos to each other, they all accomplish different things but they work together towards the same goal)
- a person (the brain is fedora, the mouth/face is drupal, the torso is camel and the limbs are microservices)
- a cerebus (3 headed dog, each head represents a different face to the data, but they all share the same body, this may be too close to the Samvera hydra metaphor though)

A lot of these may be hard to draw, but the right metaphor can say a lot even without a drawing to illustrate it. Additionally, it could be that there just isn't any metaphor that can do for 8.x what the burger did for 7.x; sometimes a well-drawn and simple system diagram can tell the story you need just fine. A metaphor is nice, but not required. Just something to think about.

**Comment by bgilling** [comment]
How about the very similar metaphor of adding apps / configuring the OS on any of our mobile devices.  An example of installing an app would be if you want to scan QR codes, and a potential system configuration could be to integrate your geo location into every picture taken.

**Comment by kstapelfeldt** [comment]
From my perspective, the Islandora sandwich was meant to communicate to users who knew what Drupal and Fedora were, but not what Islandora is. Since that time, Islandora feels like it's more recognizable as it's own entity. 

Maybe we need a communications plan that meets existing users who need to upgrade, potential new users, administrators and practitioners where they are.

+1 for retiring the lobster 
+1 for a beautiful, simplified systems diagram

**Comment by mjordan** [comment]
I'm using a (sushi) bento box in the upcoming OpenRepositories and iCamp slide decks (and @dannylamb used it in the Islandora 8 webinar slid deck). I'll post it here after those events are over for discussion.

**Comment by manez** [comment]
Having run it through a few presentation and demos now, I have to say bento box metaphor is turning out to be really useful. We haven't been labelling the parts like we did in the cheeseburger, but I'm starting to think labelling isn't a good idea anyway. We can and should have a nice clean, simplified diagram of the stack for explaining how the parts fit together. The bento box isn't a diagram; it's an overarching metaphor for highlighting how 8 differs from 7:

- It's no longer a vertical stack like the burger
- The individual components are more separated and can more easily be swapped with other components (stuff in compartments of the bento box). Also a good way to highlight how things work more asynchronously.
- We can make sure there's a shrimp tail in there somewhere, so it stays 'on brand' 😛  


image

**Comment by alexkent0** [comment]
I like the Bento box metaphor for 8. Though as I was going through the
documentation, I couldn't help but think of Islandora as a "lab" and
feeling a bit like a mad scientist with all the Drupal configuration and
setup options that you have available...this is the image I came up with:

[image: image.png]

Maybe way off, but there might be a useful metaphor here...

**Comment by mjordan** [comment]
> We can make sure there's a shrimp tail in there somewhere, so it stays 'on brand'

Niiiice.

**Comment by dannylamb** [comment]
@alexkent0 Can't see the image :(

**Comment by alexkent0** [comment]
Ok, I attached it - hopefully that works. Thanks!

**Comment by manez** [comment]
@alexkent0 lazy tip for images in GitHUb issues: if you have the image on your clipboard, you can paste it into the comment and GitHub will host and present it for viewing

**Pull request closed without merging**
