### PR TITLE
Make the Gemini lookup text less node-specific.

### PR DESCRIPTION
**Pull request by rosiel**
Great to have this available! minor edits? comments welcome. 

@Natkeeran

### CODE REVIEW

**Comment by whikloj** [comment]
@rosiel oh there is a conflict, could you rebase or press the "resolve conflicts" button please.

**Comment by rosiel** [comment]
Apparently i entirely wiped out my changes. Hmm.

**Comment by rosiel** [comment]
Well this is super confusing... because apparently my changes were already made with https://github.com/Islandora-CLAW/CLAW/pull/1084/files. No need for this PR!

**Comment by whikloj** [comment]
Well then, good work 👏

**Pull request closed without merging**
