### PR TITLE
remove any mention of 7.x-2.x, address issue #537

### PR DESCRIPTION
**Pull request by kimpham54**
Islandora-CLAW/CLAW#537

### CODE REVIEW

**Comment by kimpham54** [comment]
oh ok! tricksy

**Comment by kimpham54** [comment]
@ruebot does https://github.com/Islandora-CLAW/drupal-project need a contributing.md? are there any repositories in CLAW that don't need a contributing.md?

**Comment by kimpham54** [comment]
@ruebot should all of the CONTRIBUTING.md's have the same text in every repository? i've noticed a lot of discrepancy between CONTRIBUTING.md files.

**Comment by kimpham54** [comment]
there's extra wording in some repositories about PSR-2, PSR-4 compliance: https://github.com/Islandora-CLAW/Alpaca/blob/master/CONTRIBUTING.md#create-a-pull-request
https://github.com/Islandora-CLAW/Crayfish/blob/master/CONTRIBUTING.md#create-a-pull-request
but other ones don't have it:
https://github.com/Islandora-CLAW/CLAW/blob/master/CONTRIBUTING.md#create-a-pull-request
https://github.com/Islandora-CLAW/claw_vagrant/blob/master/CONTRIBUTING.md#create-a-pull-request

The welcome message some just refer to CLAW, while others refer to the specific repository:
https://github.com/Islandora-CLAW/claw_vagrant/blob/master/CONTRIBUTING.md#welcome
vs
https://github.com/Islandora-CLAW/islandora_collection/blob/8.x-1.x/CONTRIBUTING.md#welcome

this is the list of tasks to clean up the CONTRIBUTING.md that I've identified so far:
- remove any links that point to 7.x-2.x, make them point to master or 8.x or what the 'master' branch would be for that repository
- change any mention of "Islandora and Fedora project" to Islandora CLAW project
- remove mentions or links to use cases that point to islandora-deprecated/Islandora-Fedora4-Interest-Group
- make sure any anchor links refer to sections in the same repository, not back to the CLAW repository

additional notes:
add a contributing.md if it doesn't exist to every repository
work on separate branch
reference the original issue in the ticket
add all links in one comment for review

**Comment by manez** [comment]
generic_welcome++. I think the wording for this one: "If you are reading this document then you are interested in contributing to the Islandora CLAW. All contributions are welcome: use-cases, documentation, code, patches, bug reports, feature requests, etc. You do not need to be a programmer to speak up!" can serve for all the repos, since CLAW is both this repo and the over-arching project name.

**Comment by kimpham54** [comment]
@ruebot the additional notes are just personal notes, i'm just putting them in the comments for reference if someone needs to do a documentation audit in the future

**Pull request closed without merging**
