### PR TITLE
Broadcaster 448

### PR DESCRIPTION
**Pull request by dannylamb**
This PR updates the install to include the changes from #448.

### Testing Instructions
This will require you to spin up a new box, but since https://github.com/Islandora-CLAW/Alpaca/pull/22 won't be merged until you can test this, there's some extra hoops to jump through.  Pull in the changes from this PR and then
- `cd /path/to/CLAW/install`
- `vagrant destroy`
- `sed -i 's|git clone https://github.com/Islandora-CLAW/Alpaca.git|git clone -b broadcaster-448 https://github.com/dannylamb/Alpaca.git|' scripts/alpaca.sh`
- `vagrant up`

Then once the VM is up and ready, you can test by verifying the feature has installed itself properly.
- `/opt/karaf/bin/client`
And from within the Karaf console
```
karaf@root()> feature:list | grep islandora-connector-broadcast
islandora-connector-broadcast           | 0.1.0.SNAPSHOT   | x        | Started     | islandora-karaf-0.1.0-SNAPSHOT |
```
The X means it's been installed.

You should also verify that the bundle is in the Active state
```
karaf@root()> bundle:list | grep islandora-connector-broadcast
242 | Active |  80 | 0.1.0.SNAPSHOT     | islandora-connector-broadcast
```

We're not set up for end-to-end integration testing yet (see #455), so in lieu of that, you can drop in this blueprint file in `/opt/karaf/deploy` and watch it go:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<blueprint
        xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:cm="http://aries.apache.org/blueprint/xmlns/blueprint-cm/v1.1.0"
        xsi:schemaLocation="
      http://www.osgi.org/xmlns/blueprint/v1.0.0
      http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd">

    <camelContext id="IslandoraConnectorBroadcastTest" xmlns="http://camel.apache.org/schema/blueprint">
      <route>
        <from uri="timer:foo?period=10000"/>
        <setHeader headerName="IslandoraBroadcastRecipients">
          <constant>activemq:queue:foo,activemq:queue:bar</constant>
        </setHeader>
        <to uri="activemq:queue:islandora-connector-broadcast"/>
      </route>

      <route>
        <from uri="activemq:queue:foo"/>
          <log message="FOO"/>
      </route>

      <route>
        <from uri="activemq:queue:bar"/>
          <log message="BAR"/>
      </route>

    </camelContext>

</blueprint>
```

From your karaf console, run `log:tail` and you should see the following fly by every ten seconds:
```
2016-12-13 18:20:53,787 | INFO  | ector-broadcast] | MessageBroadcaster               | 57 - org.apache.camel.camel-core - 2.17.3 | Distributing message: ID:islandora-deux-37839-1481576415159-45:1:1:1:4 with timestamp 1481653253781
2016-12-13 18:20:53,793 | DEBUG | ector-broadcast] | msConfiguration$CamelJmsTemplate | 81 - org.apache.servicemix.bundles.spring-jms - 3.2.14.RELEASE_1 | Executing callback on JMS Session: PooledSession { ActiveMQSession {id=ID:islandora-deux-37839-1481576415159-37:1:1,started=false} java.lang.Object@63e8bbf7 }
2016-12-13 18:20:53,795 | DEBUG | ector-broadcast] | JmsConfiguration                 | 58 - org.apache.camel.camel-jms - 2.17.3 | Sending JMS message to: queue://foo with message: ActiveMQMessage {commandId = 0, responseRequired = false, messageId = null, originalDestination = null, originalTransactionId = null, producerId = null, destination = null, transactionId = null, expiration = 0, timestamp = 0, arrival = 0, brokerInTime = 0, brokerOutTime = 0, correlationId = null, replyTo = null, persistent = true, type = null, priority = 4, groupID = null, groupSequence = 0, targetConsumerId = null, compressed = false, userID = null, content = null, marshalledProperties = null, dataStructure = null, redeliveryCounter = 0, size = 0, properties = {firedTime=Tue Dec 13 18:20:53 UTC 2016, breadcrumbId=ID-islandora-deux-40947-1481576413216-14-13, CamelJmsDeliveryMode=2, ca_DOT_islandora_DOT_alpaca_DOT_connector_DOT_broadcast_DOT_recipients=activemq:queue:foo,activemq:queue:bar}, readOnlyProperties = false, readOnlyBody = false, droppable = false, jmsXGroupFirstForConsumer = false}
2016-12-13 18:20:53,806 | DEBUG | JmsConsumer[foo] | faultJmsMessageListenerContainer | 81 - org.apache.servicemix.bundles.spring-jms - 3.2.14.RELEASE_1 | Received message of type [class org.apache.activemq.command.ActiveMQMessage] from consumer [PooledMessageConsumer { ActiveMQMessageConsumer { value=ID:islandora-deux-37839-1481576415159-41:1:1:1, started=true } }] of session [PooledSession { ActiveMQSession {id=ID:islandora-deux-37839-1481576415159-41:1:1,started=true} java.lang.Object@f50d1b0 }]
2016-12-13 18:20:53,806 | DEBUG | JmsConsumer[foo] | EndpointMessageListener          | 58 - org.apache.camel.camel-jms - 2.17.3 | Endpoint[activemq://queue:foo] consumer received JMS message: ActiveMQMessage {commandId = 9, responseRequired = true, messageId = ID:islandora-deux-37839-1481576415159-37:1:1:1:5, originalDestination = null, originalTransactionId = null, producerId = ID:islandora-deux-37839-1481576415159-37:1:1:1, destination = queue://foo, transactionId = null, expiration = 0, timestamp = 1481653253802, arrival = 0, brokerInTime = 1481653253803, brokerOutTime = 1481653253803, correlationId = null, replyTo = null, persistent = true, type = null, priority = 4, groupID = null, groupSequence = 0, targetConsumerId = null, compressed = false, userID = null, content = null, marshalledProperties = org.apache.activemq.util.ByteSequence@2a7db171, dataStructure = null, redeliveryCounter = 0, size = 0, properties = {CamelJmsDeliveryMode=2, firedTime=Tue Dec 13 18:20:53 UTC 2016, breadcrumbId=ID-islandora-deux-40947-1481576413216-14-13, ca_DOT_islandora_DOT_alpaca_DOT_connector_DOT_broadcast_DOT_recipients=activemq:queue:foo,activemq:queue:bar}, readOnlyProperties = true, readOnlyBody = true, droppable = false, jmsXGroupFirstForConsumer = false}
2016-12-13 18:20:53,806 | INFO  | JmsConsumer[foo] | route18                          | 57 - org.apache.camel.camel-core - 2.17.3 | FOO
2016-12-13 18:20:53,810 | DEBUG | ector-broadcast] | msConfiguration$CamelJmsTemplate | 81 - org.apache.servicemix.bundles.spring-jms - 3.2.14.RELEASE_1 | Executing callback on JMS Session: PooledSession { ActiveMQSession {id=ID:islandora-deux-37839-1481576415159-39:1:1,started=false} java.lang.Object@23023150 }
2016-12-13 18:20:53,811 | DEBUG | ector-broadcast] | JmsConfiguration                 | 58 - org.apache.camel.camel-jms - 2.17.3 | Sending JMS message to: queue://bar with message: ActiveMQMessage {commandId = 0, responseRequired = false, messageId = null, originalDestination = null, originalTransactionId = null, producerId = null, destination = null, transactionId = null, expiration = 0, timestamp = 0, arrival = 0, brokerInTime = 0, brokerOutTime = 0, correlationId = null, replyTo = null, persistent = true, type = null, priority = 4, groupID = null, groupSequence = 0, targetConsumerId = null, compressed = false, userID = null, content = null, marshalledProperties = null, dataStructure = null, redeliveryCounter = 0, size = 0, properties = {firedTime=Tue Dec 13 18:20:53 UTC 2016, breadcrumbId=ID-islandora-deux-40947-1481576413216-14-13, CamelJmsDeliveryMode=2, ca_DOT_islandora_DOT_alpaca_DOT_connector_DOT_broadcast_DOT_recipients=activemq:queue:foo,activemq:queue:bar}, readOnlyProperties = false, readOnlyBody = false, droppable = false, jmsXGroupFirstForConsumer = false}
2016-12-13 18:20:53,816 | DEBUG | JmsConsumer[bar] | faultJmsMessageListenerContainer | 81 - org.apache.servicemix.bundles.spring-jms - 3.2.14.RELEASE_1 | Received message of type [class org.apache.activemq.command.ActiveMQMessage] from consumer [PooledMessageConsumer { ActiveMQMessageConsumer { value=ID:islandora-deux-37839-1481576415159-43:1:1:1, started=true } }] of session [PooledSession { ActiveMQSession {id=ID:islandora-deux-37839-1481576415159-43:1:1,started=true} java.lang.Object@2d38faec }]
2016-12-13 18:20:53,817 | DEBUG | JmsConsumer[bar] | EndpointMessageListener          | 58 - org.apache.camel.camel-jms - 2.17.3 | Endpoint[activemq://queue:bar] consumer received JMS message: ActiveMQMessage {commandId = 9, responseRequired = true, messageId = ID:islandora-deux-37839-1481576415159-39:1:1:1:5, originalDestination = null, originalTransactionId = null, producerId = ID:islandora-deux-37839-1481576415159-39:1:1:1, destination = queue://bar, transactionId = null, expiration = 0, timestamp = 1481653253813, arrival = 0, brokerInTime = 1481653253813, brokerOutTime = 1481653253814, correlationId = null, replyTo = null, persistent = true, type = null, priority = 4, groupID = null, groupSequence = 0, targetConsumerId = null, compressed = false, userID = null, content = null, marshalledProperties = org.apache.activemq.util.ByteSequence@8159e60, dataStructure = null, redeliveryCounter = 0, size = 0, properties = {CamelJmsDeliveryMode=2, firedTime=Tue Dec 13 18:20:53 UTC 2016, breadcrumbId=ID-islandora-deux-40947-1481576413216-14-13, ca_DOT_islandora_DOT_alpaca_DOT_connector_DOT_broadcast_DOT_recipients=activemq:queue:foo,activemq:queue:bar}, readOnlyProperties = true, readOnlyBody = true, droppable = false, jmsXGroupFirstForConsumer = false}
2016-12-13 18:20:53,817 | INFO  | JmsConsumer[bar] | route19                          | 57 - org.apache.camel.camel-core - 2.17.3 | BAR
2016-12-13 18:20:53,824 | DEBUG | ector-broadcast] | MulticastProcessor               | 57 - org.apache.camel.camel-core - 2.17.3 | Done sequential processing 2 exchanges
```

### CODE REVIEW

**Comment by dannylamb** [comment]
@Islandora-CLAW/committers Now that #458 has landed, this is good to go.  Can someone else please verify the install for me?

As always, _please squash and merge_ if this meets expectations.

**Comment by DiegoPino** [comment]
@dannylamb will test, since i'm devopping this week =)

**Comment by DiegoPino** [comment]
@dannylamb This is not working for me:
>
==> default: 1554 [sshd-SshClient[383534aa]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at /0.0.0.0:8101 presented unverified RSA key: 4b:56:5a:95:e3:ca:3e:53:dd:0b:e4:32:28:cb:60:5c
==> default: Adding feature url file:/home/ubuntu/Alpaca/karaf/build/resources/main/features.xml
==> default: Error executing command: Error
==> default: 
==> default:

**Comment by DiegoPino** [comment]
Yeah, still have it:  
> drwxr-xr-x  3 root   root      4096 Dec 19 14:46 .m2

**Comment by dannylamb** [comment]
@DiegoPino Crud... Even when compiled as the ubuntu user, it still is getting set to root somehow, even after chowning...  I'll spin up another and see if I can sort it out.

**Comment by whikloj** [comment]
Worked for me
```
==> default: Installing Alpaca
==> default: 931 [sshd-SshClient[383534aa]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at /0.0.0.0:8101 presented unverified RSA key: 85:ea:3b:67:db:e2:b4:84:6e:dd:d1:dd:6f:23:f1:72
==> default: Adding feature url file:/home/ubuntu/Alpaca/karaf/build/resources/main/features.xml
==> default: 
==> default: 
```
```
2016-12-19 20:14:33,481 | INFO  | ector-broadcast] | BroadcastRouter                  | 186 - ca.islandora.alpaca.islandora-connector-broadcast - 0.1.0.SNAPSHOT | Distributing message: ID:islandora-deux-44997-1482177539714-13:1:1:1:3 with timestamp 1482178473474
2016-12-19 20:14:33,482 | DEBUG | ector-broadcast] | msConfiguration$CamelJmsTemplate | 201 - org.apache.servicemix.bundles.spring-jms - 4.2.5.RELEASE_1 | Executing callback on JMS Session: PooledSession { ActiveMQSession {id=ID:islandora-deux-33373-1482177541890-5:1:1,started=false} java.lang.Object@1fabb0d9 }
2016-12-19 20:14:33,483 | DEBUG | ector-broadcast] | JmsConfiguration                 | 58 - org.apache.camel.camel-jms - 2.17.3 | Sending JMS message to: queue://foo with message: ActiveMQMessage {commandId = 0, responseRequired = false, messageId = null, originalDestination = null, originalTransactionId = null, producerId = null, destination = null, transactionId = null, expiration = 0, timestamp = 0, arrival = 0, brokerInTime = 0, brokerOutTime = 0, correlationId = null, replyTo = null, persistent = true, type = null, priority = 4, groupID = null, groupSequence = 0, targetConsumerId = null, compressed = false, userID = null, content = null, marshalledProperties = null, dataStructure = null, redeliveryCounter = 0, size = 0, properties = {firedTime=Mon Dec 19 20:14:33 UTC 2016, breadcrumbId=ID-islandora-deux-43528-1482177537635-5-9, IslandoraBroadcastRecipients=activemq:queue:foo,activemq:queue:bar, CamelJmsDeliveryMode=2}, readOnlyProperties = false, readOnlyBody = false, droppable = false, jmsXGroupFirstForConsumer = false}
2016-12-19 20:14:33,490 | DEBUG | JmsConsumer[foo] | faultJmsMessageListenerContainer | 201 - org.apache.servicemix.bundles.spring-jms - 4.2.5.RELEASE_1 | Received message of type [class org.apache.activemq.command.ActiveMQMessage] from consumer [PooledMessageConsumer { ActiveMQMessageConsumer { value=ID:islandora-deux-44997-1482177539714-9:1:1:1, started=true } }] of session [PooledSession { ActiveMQSession {id=ID:islandora-deux-44997-1482177539714-9:1:1,started=true} java.lang.Object@3a1e1bba }]
2016-12-19 20:14:33,494 | DEBUG | JmsConsumer[foo] | EndpointMessageListener          | 58 - org.apache.camel.camel-jms - 2.17.3 | Endpoint[activemq://queue:foo] consumer received JMS message: ActiveMQMessage {commandId = 7, responseRequired = true, messageId = ID:islandora-deux-33373-1482177541890-5:1:1:1:3, originalDestination = null, originalTransactionId = null, producerId = ID:islandora-deux-33373-1482177541890-5:1:1:1, destination = queue://foo, transactionId = null, expiration = 0, timestamp = 1482178473487, arrival = 0, brokerInTime = 1482178473487, brokerOutTime = 1482178473488, correlationId = null, replyTo = null, persistent = true, type = null, priority = 4, groupID = null, groupSequence = 0, targetConsumerId = null, compressed = false, userID = null, content = null, marshalledProperties = org.apache.activemq.util.ByteSequence@620084d9, dataStructure = null, redeliveryCounter = 0, size = 0, properties = {CamelJmsDeliveryMode=2, firedTime=Mon Dec 19 20:14:33 UTC 2016, breadcrumbId=ID-islandora-deux-43528-1482177537635-5-9, IslandoraBroadcastRecipients=activemq:queue:foo,activemq:queue:bar}, readOnlyProperties = true, readOnlyBody = true, droppable = false, jmsXGroupFirstForConsumer = false}
2016-12-19 20:14:33,494 | INFO  | JmsConsumer[foo] | route6                           | 57 - org.apache.camel.camel-core - 2.17.3 | FOO
2016-12-19 20:14:33,497 | DEBUG | ector-broadcast] | msConfiguration$CamelJmsTemplate | 201 - org.apache.servicemix.bundles.spring-jms - 4.2.5.RELEASE_1 | Executing callback on JMS Session: PooledSession { ActiveMQSession {id=ID:islandora-deux-33373-1482177541890-7:1:1,started=false} java.lang.Object@670d672a }
2016-12-19 20:14:33,498 | DEBUG | ector-broadcast] | JmsConfiguration                 | 58 - org.apache.camel.camel-jms - 2.17.3 | Sending JMS message to: queue://bar with message: ActiveMQMessage {commandId = 0, responseRequired = false, messageId = null, originalDestination = null, originalTransactionId = null, producerId = null, destination = null, transactionId = null, expiration = 0, timestamp = 0, arrival = 0, brokerInTime = 0, brokerOutTime = 0, correlationId = null, replyTo = null, persistent = true, type = null, priority = 4, groupID = null, groupSequence = 0, targetConsumerId = null, compressed = false, userID = null, content = null, marshalledProperties = null, dataStructure = null, redeliveryCounter = 0, size = 0, properties = {firedTime=Mon Dec 19 20:14:33 UTC 2016, breadcrumbId=ID-islandora-deux-43528-1482177537635-5-9, IslandoraBroadcastRecipients=activemq:queue:foo,activemq:queue:bar, CamelJmsDeliveryMode=2}, readOnlyProperties = false, readOnlyBody = false, droppable = false, jmsXGroupFirstForConsumer = false}
2016-12-19 20:14:33,503 | DEBUG | JmsConsumer[bar] | faultJmsMessageListenerContainer | 201 - org.apache.servicemix.bundles.spring-jms - 4.2.5.RELEASE_1 | Received message of type [class org.apache.activemq.command.ActiveMQMessage] from consumer [PooledMessageConsumer { ActiveMQMessageConsumer { value=ID:islandora-deux-44997-1482177539714-11:1:1:1, started=true } }] of session [PooledSession { ActiveMQSession {id=ID:islandora-deux-44997-1482177539714-11:1:1,started=true} java.lang.Object@7da4683b }]
2016-12-19 20:14:33,504 | DEBUG | JmsConsumer[bar] | EndpointMessageListener          | 58 - org.apache.camel.camel-jms - 2.17.3 | Endpoint[activemq://queue:bar] consumer received JMS message: ActiveMQMessage {commandId = 7, responseRequired = true, messageId = ID:islandora-deux-33373-1482177541890-7:1:1:1:3, originalDestination = null, originalTransactionId = null, producerId = ID:islandora-deux-33373-1482177541890-7:1:1:1, destination = queue://bar, transactionId = null, expiration = 0, timestamp = 1482178473499, arrival = 0, brokerInTime = 1482178473499, brokerOutTime = 1482178473500, correlationId = null, replyTo = null, persistent = true, type = null, priority = 4, groupID = null, groupSequence = 0, targetConsumerId = null, compressed = false, userID = null, content = null, marshalledProperties = org.apache.activemq.util.ByteSequence@576f5413, dataStructure = null, redeliveryCounter = 0, size = 0, properties = {CamelJmsDeliveryMode=2, firedTime=Mon Dec 19 20:14:33 UTC 2016, breadcrumbId=ID-islandora-deux-43528-1482177537635-5-9, IslandoraBroadcastRecipients=activemq:queue:foo,activemq:queue:bar}, readOnlyProperties = true, readOnlyBody = true, droppable = false, jmsXGroupFirstForConsumer = false}
2016-12-19 20:14:33,505 | INFO  | JmsConsumer[bar] | route7                           | 57 - org.apache.camel.camel-core - 2.17.3 | BAR
2016-12-19 20:14:33,507 | DEBUG | ector-broadcast] | MulticastProcessor               | 57 - org.apache.camel.camel-core - 2.17.3 | Done sequential processing 2 exchanges
```

**Comment by DiegoPino** [comment]
@dannylamb nope. Went clean again, all the way and this is the third time:
==> default: Installing Islandora Triplestore Indexer
==> default: 1364 [sshd-SshClient[383534aa]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at /0.0.0.0:8101 presented unverified RSA key: c3:83:bd:19:53:14:e8:9f:89:9c:50:d2:cf:7d:7a:b0
==> default: Adding feature url file:/home/ubuntu/Alpaca/karaf/build/resources/main/features.xml
==> default: Error executing command: Error
==> default: 
==> default: 

Sorry, i suppose i can't be that wrong!. Made sure i was following all the steps. Any other ideas?

OSX
Vagrant 1.8.1
ubuntu/xenial 20161213.0.0
VBox 5.0.26r108824

**Comment by dannylamb** [comment]
@DiegoPino Just checking my verification vagrant up and it's ok for me as well.  CLAW commit is f0d26134455e4e9b67c736d2f10dc8a2c01a07d8, Alpaca commit on vagrant box is 83a4603174d19430ef9edc12f3edbb3760167447.

I'm going to try obsessively chowning the local maven repository before and after compilation, AND before deploying the features file and see if that works.  If it does, I'll try and whittle it down to where it's going wrong so I don't have a bunch of unnecessary chowns floating around in the install.

**Comment by DiegoPino** [comment]
@dannylamb i'm probably not following the instructions correctly, can't imagine a different scenario. So you are fine to merge, don't be stopped by me.

**Comment by dannylamb** [comment]
@whikloj If you're cool with this, can you merge it and Islandora-CLAW/Alpaca#22 as well?

**Comment by whikloj** [comment]
@ruebot @Natkeeran @MarcusBarnes @bryjbrown 
We need a third tester, someone to break the tie. Could one or more of you try this PR and see if it works for you.

**Comment by dannylamb** [comment]
@whikloj++

**Comment by DiegoPino** [comment]
@ruebot thanks! I'm already doing it again from 0 (really 0, destroyed all my VM by mistake!). If i got this passed, are you ok if i merge?

**Comment by DiegoPino** [comment]
Ok, done:
Works, passed. I just needed to rm -rf my whole VM folder... 😨 

> ==> default: mysql-connector-java-6.0.4/src/test/java/testsuite/x/TestMysqlxRequirements.java
==> default: Installing ID Mapping Service
==> default: 815 [sshd-SshClient[383534aa]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at /0.0.0.0:8101 presented unverified RSA key: 55:20:da:1d:94:8e:b3:f2:5a:dc:06:c8:3d:a0:b9:fb
==> default: Adding feature url mvn:edu.amherst.acdc/acrepo-karaf/1.0.6/xml/features
==> default: 
==> default: 
==> default: Installing Alpaca
==> default: 1431 [sshd-SshClient[383534aa]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at /0.0.0.0:8101 presented unverified RSA key: 55:20:da:1d:94:8e:b3:f2:5a:dc:06:c8:3d:a0:b9:fb
==> default: Adding feature url file:/home/ubuntu/Alpaca/karaf/build/resources/main/features.xml
==> default: 
==> default: 
==> default: Running provisioner: shell...

**Comment by DiegoPino** [comment]
@ruebot, i know the feeling 😢  i think i made a mistake (4 times, not once) that lead to that, because in the instructions there is a subtly implied action "Pull in the changes from this PR and then" that i probably did wrong in favor of the manual action. I think i did not that part correctly because the instructions further down looked more tempting 😄 for me.

So if you do now a

vagrant destroy
vagrant git reset --hard
git checkout -b dannylamb-broadcaster-448 master
git pull https://github.com/dannylamb/CLAW.git broadcaster-448

then the manual changes in scripts/alpaca.sh
vagrant up

it should work, maybe, at least it did this time for me.

**Comment by DiegoPino** [comment]
@ruebot++ no idiot at all. It was not easy to follow.

**Pull request merged**
