### PR TITLE
Add weekly Tech Calls to contributing. Address #98

### PR DESCRIPTION
**Pull request by ruebot**
See #98 

@Islandora-Labs/7-x-2-x-committers and @Islandora-Labs/7-x-2-x-sprinters, please let me know what you think.

cheers!

### CODE REVIEW

**Comment by dltj** [comment]
What day of the week do the tech calls occur.  Tuesday's, right?

**Comment by manez** [comment]
Wednesdays. In fact - today is the first one! 1PM Eastern.

**Comment by dltj** [comment]
+1

**Comment by DiegoPino** [comment]
:+1:

**Pull request merged**
