### PR TITLE
Claw docs restructure

### PR DESCRIPTION
**Pull request by rosiel**
It's still a mess, and will be for a while, but I propose:
- getting rid of the submodules and included readmes (also, they didn't deploy, because they used an old git protocol that didn't work anymore and I couldn't figure out how to update them so I blew them away and we should re-add them if necessary.
- restructuring the user docs to focus on how an islandora object is constructed.

STILL not done at this point, and let me know if we should do this before merging, so that this isn't a giant mess,
- including a good overview and list of the Components (honestly i don't have a good grasp of them yet)
- including more than the 3 lines in the summary on how to spin up a Vagrant.
- include the orphan files (i don't think I make them orphans): islandora/drupal-bundle-configurations.md and islandora/rdf-mapping.md

### CODE REVIEW

**Comment by whikloj** [comment]
I am wondering about all the parts (drupal modules, alpaca, api-x, etc), do we not want to keep the individual parts so people can understand the "stack". This is one of the main learning goals for people in the 7.x camps I have been at. So maybe we still need some sort of section to describe how the stack fits together.

**Comment by rosiel** [comment]
We absolutely do! I haven' had a chance to get back to this PR, but i'm intending to "put back" the parts, and figure out how to present it in a way that lets the un-initiated user make sense of our lovely codenames in a larger framework. @whikloj 💯

**Comment by rosiel** [comment]
In fact @dannylamb  made a fantastic architecture diagram I"ll be showing a room full of research data management people in about... 50 minutes... do you think it can go in as-is? 
screen shot 2019-01-23 at 1 42 32 pm

**Comment by whikloj** [comment]
Ooooooooo thats nice!!!

**Comment by rosiel** [comment]
> @rosiel Let's keep the .gitmodules file. Even though we're not including the individual READMEs, I still plan on using this to lock versions of the submodules in time for releasing.

Ok, uh, i added them back in using `git submodule add` so they're not locked down to versions at the moment. is that ok?

**Comment by dannylamb** [comment]
No, you're cool.  This'll lock 'em down to latest.

You can still clobber the READMEs if you want.  You didn't have to add those back in.

**Pull request merged**
