### PR TITLE
Move to Solr 6.2.1; Address #379.

### PR DESCRIPTION
**Pull request by ruebot**
See: https://github.com/Islandora-CLAW/CLAW/issues/379

@Islandora-CLAW/committers

### CODE REVIEW

**Comment by whikloj** [comment]
I'll try this one too, have to figure out why nothing works for me anymore.

**Comment by whikloj** [comment]
Okay, first time blazegraph did not download. But the second run worked. So I think this is a 👍

**Comment by dannylamb** [comment]
`vagrant up`

**Comment by dannylamb** [comment]
:+1: Solr is up and running

**Pull request merged**
