### PR TITLE
Fixed image link to image04.png.

### PR DESCRIPTION
**Pull request by mjordan**

### CODE REVIEW

**Comment by mjordan** [comment]
@ruebot nope, go ahead.

**Comment by dannylamb** [comment]
Sry, thought your pull subsumed this based on conversation.

**Comment by mjordan** [comment]
I'll close this PR and open a new one, but am just stepping out now and won't get to it until later today. Is that OK?

**Comment by mjordan** [comment]
To be honest, I haven't found or made the time to gain enough confidence with rebasing to complete this. Seems like a lot of overhead to add a single character to a readme. Wouldn't someone just making the change in the github GUI editing tools be enough?

**Comment by mjordan** [comment]
Sweet, thanks, will do now.

**Pull request closed without merging**
