### PR TITLE
Install D8 and modules using composer

### PR DESCRIPTION
**Pull request by dannylamb**
Install PR for #474 and #475 

### Testing instructions
* Pull down the code from this PR
```
git checkout -b dannylamb-composer master
git pull https://github.com/dannylamb/CLAW.git composer
```
* visit https://github.com/settings/tokens and get an oauth token (check the 'repos' checkbox when making it)
* put your token in `install/configs/variables` as the `GITHUB_TOKEN` variable (it's set to 'changeme' by default)
* vagrant up

Functionality should remain the same.  I tested by creating, editing, and then deleting a fedora resource, and made sure the rules actions were firing.

### CODE REVIEW

**Comment by dannylamb** [comment]
Initial testing has found that we hit a rate limit for github requests through composer.  We can fix that for devs by allowing them to provide their authentication creds in configuration.  For users without github accounts, we need to provide stable releases through packagist.

**Comment by dannylamb** [comment]
This works right now using an oauth token from github.  I'll update the README in this pull later.

Long term, the solution is just to get on packagist and have small, frequent releases.  I'm already bringing this up at the next committers meeting https://github.com/Islandora-CLAW/CLAW/wiki/January-18%2C-2017

**Comment by whikloj** [comment]
Ok, new vagrant with an OAuth token and this branch ended up with a loop trying to download restui
```
==> default: restui was not found.                                                  [warning]
==> default: The following projects provide some or all of the extensions not            [ok]
==> default: found:
==> default: restui
==> default: Would you like to download them? (y/n): 
==> default: y
==> default: This codebase is assembled with Composer instead of Drush. Use           [error]
==> default: `composer update` and `composer require` instead of `drush
==> default: pm-updatecode` and `drush pm-download`. You may override this error
==> default: by using the --pm-force option.
==> default: restui was not found.                                                  [warning]
==> default: The following projects provide some or all of the extensions not            [ok]
==> default: found:
==> default: restui
==> default: Would you like to download them? (y/n): 
==> default: y
==> default: This codebase is assembled with Composer instead of Drush. Use           [error]
==> default: `composer update` and `composer require` instead of `drush
==> default: pm-updatecode` and `drush pm-download`. You may override this error
==> default: by using the --pm-force option.
```
So either we add the `--pm-force` or change the `drush dl` to `composer require`.

Preferences?

**Comment by whikloj** [comment]
Just as a note I modified the restui one to say
```
composer require "drupal/restui:~8.x-1.0"
```
and then got stuck on a loop at the next one. So this is not limited to restui.

**Comment by DiegoPino** [comment]
@whikloj I say, let's talk about this tomorrow on CLAW tech call?I feel our approach is not working or we are doing something wrong?

**Comment by dannylamb** [comment]
@whikloj That loop happens if you try and `drush dl` something.

**Comment by DiegoPino** [comment]
@whikloj we should swich to installing drush globally
 `composer global require drush/drush `

**Comment by whikloj** [comment]
This was all my mistake, I cloned the wrong `drupal-project` repo. Stay tuned.

**Comment by whikloj** [comment]
👍  ok now it works, if you use @dannylamb's drupal-project branch.

**Pull request merged**
