### PR TITLE
Fix TravisCI for https://github.com/Islandora-CLAW/CLAW/issues/643 re…

### PR DESCRIPTION
**Pull request by ruebot**
**GitHub Issue**: https://github.com/Islandora-CLAW/islandora/pull/63#issuecomment-305485553

# What does this Pull Request do?

Enables the rest Drupal module.

# What's new?
Above.

# How should this be tested?

Merge it and I'll restart TravisCI on the Drupal modules.

# Interested parties
@dannylamb

### CODE REVIEW

**Comment by jonathangreen** [comment]
I wonder if we should be working out whatever dependancy issues we are having instead of forcing us to enable rest before we enable the Islandora module? 

When I download a module I kind of expect to be able to drush en it without having to enable other modules first. Won't that be kind of confusing for folks installing islandora in the future? 

Maybe I'm misunderstanding the issue. I'm always alarmed though, when we just force enable a module.

**Comment by dannylamb** [comment]
@jonathangreen Ah just seeing this comment now.  Yeah, this is meant to be a short-term fix.  Let's keep #643 open until we get it sorted out properly.

For context, we need to modify the rest resource config for nodes that the `rest` module provides.  We can't provide our own because the two will conflict.  So I'm editing it in hook_install right now, which probably isn't the best place.   I'm loathe to introduce a hook_update_N to do something not related to an update at all.  Do you know of a better place to do it?

**Comment by whikloj** [comment]
@dannylamb so is `rest` not enabled by our `drupal-project` fork? I'm not understanding what module is not enabled when we try this?

**Comment by dannylamb** [comment]
@whikloj `rest` is installed when installing islandora since it's declared as a dependency.  It can be pre-installed before installing islandora, so we needed to check that case as well.

But it's all moot at this point because I moved to using another hook.  Instead of `hook_install` I'm using `hook_modules_installed`, which executes _every_ time any module is installed, which covers both cases.

**Pull request merged**
