### PR TITLE
7.x 2.x issue 114

### PR DESCRIPTION
**Pull request by nigelgbanks**
For Issue #114

### CODE REVIEW

**Comment by nigelgbanks** [comment]
@DiegoPino We can, although the title doesn't auto link like it will in the description, so we can potentially do both.

**Comment by whikloj** [comment]
I think it's good the way it is. :+1:

**Comment by nigelgbanks** [comment]
Melissa, found some grammar problems https://github.com/Islandora-CLAW/chullo/pull/26 and I'll add the title bit in too, I just got side tracked with other problems over the last few days (Visa stuff)

**Comment by whikloj** [comment]
:+1:

**Pull request merged**
